### ISSUE TITLE
Help in creating height adjusting multiline textview

### ISSUE THREAD

**Issue by unpluggedk** [Eldorado234/PAYFormBuilder#11]
Hello, first of all, thanks for the great library.

I am in need of one additional feature, which I am glad to do and add to the library and contribute, but I need some help :(

Simply, I need a dynamic height adjusting textview cell.
Using addTextViewWithPlaceholder, changing height of the textview frame seems to change the height in static cell. 

Can you give me some directions on where to begin with this?

Thanks heaps !

**Comment by Eldorado234** [comment]
Hey @unpluggedk, do you need further information for implementing this feature? Is there anything I could do to help you?

**Comment by unpluggedk** [comment]
Oh, I'm sorry, had a major errand. 
Will ask you if I come across a question. Planning on getting working on this within a week.
Thanks!

**Comment by unpluggedk** [comment]
Hey @Eldorado234,
So far, I am able to have an adjustable textview so the height changes dynamically.
However, the remaining issue is to update the cells that follow the adjustable view.

for example./  
     textview(adjustable)
    ----------------------------
     other field #A
    ----------------------------
     other field #B

if the top cell gets adjusted, it covers the below cells after it expands.
what do you think is the best way to shift them also?

**Comment by unpluggedk** [comment]
The simplest I believe is to simply reload the data from the tableview. 

So, when there has been a change in cell height,  post notification through [NSNotificationCenter defaultCenter]

and at PAYFormTableViewController, add an observer, and simply do [tablaview reloaddata] once it is received.

What do you think?

**Comment by unpluggedk** [comment]
Done, 
I simply used notifications to the PAYFormTableViewController to handle begin/end updates. 
Will do a pull request shortly :)

Thsnk!
